---
title: "soil_index"
author: "Rose Abramoff"
date: "9/15/2017"
output: html_document
---
#load Colin's SOC data - used with permission
```{r}
sf <- read.csv("/Users/rzabramoff/Dropbox (Climate)/External Collaborations/ISCN/Allison/SOCData_Averilletal2014Nature.csv")
```

#load Allison's N min data
```{r}
nf <- read.csv("/Users/rzabramoff/Dropbox (Climate)/External Collaborations/ISCN/Allison/Nmin_data_UpdateForRose_20170922.csv")
pf <- read.csv("/Users/rzabramoff/Dropbox (Climate)/External Collaborations/ISCN/Allison/HedleyP_database_updateforRose_20170927.csv")
```

#Convert values to index
```{r}
#SOCnums <- sf$carbon.1m
#SOCnums <- SOCnums[!is.na(SOCnums)] #remove NAs
#nf$NminNum <- as.numeric(as.character(nf$Nmin_g_m2_yr_OA_mean))
#Nnums <- nf$NminNum[!is.na(nf$NminNum)] #remove NAs
#Nnums <- Nnums[Nnums < 400 & Nnums > -200] #remove 2 outliers
#Claynums <- sf$clay.1m
#Claynums <- Claynums[!is.na(Claynums)] #remove NAs

SOCnums <- sf[sf$LandUseType==c("forest","grass","undisturbed"),]$carbon.1m
SOCnums <- SOCnums[!is.na(SOCnums)] #remove NAs
NminNums <- as.numeric(as.character(nf[nf$LandUseType==c("forest","grass","undisturbed"),]$Nmin_g_m2_yr_OA_mean))
Nnums <- NminNums[!is.na(NminNums)] #remove NAs
Nnums <- Nnums[Nnums < 400 & Nnums > -200] #remove 2 outliers
Claynums <- sf[sf$LandUseType==c("forest","grass","undisturbed"),]$clay.1m
Claynums <- Claynums[!is.na(Claynums)] #remove NAs

range01 <- function(x){(x-min(x))/(max(x)-min(x))}
rangeSOC <- function(x){(x-min(SOCnums))/(max(SOCnums)-min(SOCnums))}
rangeNmin <- function(x){(x-min(Nnums))/(max(Nnums)-min(Nnums))}
rangeClay <- function(x){(x-min(Claynums))/(max(Claynums)-min(Claynums))}

W.Index <- function(s,n,c,ws,wn,wc){
SOCindex <- rangeSOC(EnterYourSOCValue)
Nindex <- rangeNmin(EnterYourNminValue)
Clayindex <- rangeClay(EnterYourClayValue)
windex <- (SOCindex*ws + Nindex*wn + Clayindex*wc)/3
return(windex)
}
save.image(file="/Users/rzabramoff/Dropbox (Climate)/External Collaborations/ISCN/SoilIndex.Rdata")
```

#Preliminary Index from 0-1
```{r}
range(SOCnums)
range(Nnums)
range(Claynums)
EnterYourSOCValue <- 100 #in gC/dm3 - same as kg/m3
EnterYourNminValue <- 30 #in g/m2/yr for OA horizons
EnterYourClayValue <- 60 #in %
SOCWeight <- 1
NminWeight <- 1
ClayWeight <- 1

W.Index(EnterYourSOCValue,EnterYourNminValue,EnterYourClayValue,SOCWeight,NminWeight,ClayWeight)
```

#Explore ISCN SOC data
```{r}
summary(sf$carbon.1m) #kgC/m2
hist(sf$carbon.1m,  xlim = c(0,100), breaks=100, xlab=expression("SOC (kgC/m2)"), main="Soil Organic Carbon")

#possible index by quartiles: 0-2.6 low, 2.6-6 med, 6-14.9 good, 14.9-1250 high

summary(sf$LandUseType)

require(ggplot2)
ggplot(sf, aes(carbon.1m)) +
  geom_density()
#takes a while:
ggplot(sf, aes(carbon.1m, fill=LandUseType)) +
  stat_density(position="identity", alpha=0.7)

ggplot(sf, aes(clay.1m)) +
  geom_density()
#takes a while:
ggplot(sf, aes(clay.1m, fill=LandUseType)) +
  stat_density(position="identity", alpha=0.7)
```

#Explore N data
```{r}
summary(as.numeric(as.character(nf$Nmin_g_m2_yr_O_mean)))
summary(as.numeric(as.character(nf$Nmin_g_m2_yr_A_mean)))
summary(as.numeric(as.character(nf$Nmin_g_m2_yr_OA_mean))) #g/m2/horizon

hist(as.numeric(as.character(nf$Nmin_g_m2_yr_O_mean)), xlim = c(0,100), breaks=100, xlab=expression("Nmin (g/m2/y O horizon)"))

require(ggplot2)
ggplot(nf, aes(as.numeric(as.character(nf$Nmin_g_m2_yr_O_mean)))) +
  geom_density()

ggplot(nf, aes(NminNum, fill=LandUseType)) +
  stat_density(position="stack") +
  xlim(-10,60) +
  xlab("N mineralization (g/m2/y) - OA horizon")
```

```
Below is extra code that I'm not using at the moment
```

#load WoSIS data
```{r}
df <- read.table("/Users/rzabramoff/Dropbox (Climate)/External Collaborations/ISCN/WoSIS_2016_July/wosis_201607_profiles.txt", sep="\t", header=T)
att <- read.table("/Users/rzabramoff/Dropbox (Climate)/External Collaborations/ISCN/WoSIS_2016_July/wosis_201607_attributes.txt", sep="\t", header=T)
lay <- read.table("/Users/rzabramoff/Dropbox (Climate)/External Collaborations/ISCN/WoSIS_2016_July/wosis_201607_layers.txt", sep="\t", header=T, fill=T)
```

#Explore WOSIS SOC data
```{r}
summary(lay$orgc_value_avg)
hist(lay$orgc_value_avg, xlim = c(0,100), breaks=100, xlab=expression("SOC (gC/kg)"))
hist(lay$bdws_value_avg) #bulk density of whole soil kg/dm3

hist(lay$orgc_value_avg*lay$bdws_value_avg,  xlim = c(0,100), breaks=100, xlab=expression("SOC (gC/dm3)"), main="Soil Organic Carbon") #same as kg/m3

summary(lay$orgc_value_avg*lay$bdws_value_avg)
#possible index by quartiles: 0-2.6 low, 2.6-6 med, 6-14.9 good, 14.9-1250 high

require(ggplot2)
lay$soc_estimate <- lay$orgc_value_avg*lay$bdws_value_avg
ggplot(lay, aes(soc_estimate)) +
  geom_density()
#takes a while:
#ggplot(lay, aes(soc_estimate, fill=orgc_profile_code)) +
#  stat_density(position="stack")
```

##Explore soil organic carbon data
```{r}
summary(lay$orgc_value_avg)
hist(lay$orgc_value_avg, xlim = c(0,100), breaks=100, xlab=expression("SOC (gC/kg)"))
hist(lay$bdws_value_avg) #bulk density of whole soil kg/dm3

hist(lay$orgc_value_avg*lay$bdws_value_avg,  xlim = c(0,100), breaks=100, xlab=expression("SOC (gC/dm3)"), main="Soil Organic Carbon") #same as kg/m3

summary(lay$orgc_value_avg*lay$bdws_value_avg)
#possible index by quartiles: 0-2.6 low, 2.6-6 med, 6-14.9 good, 14.9-1250 high

#no land use type, but location and soil type
#summary(df$cfao_soil_unit) #fao
#summary(df$cfao_major_group)
#summary(df$cstx_great_group) #soil tax
#summary(df$cwrb_reference_soil_group) #world reference base
#summary(df$cwrb_prefix_qualifier)
#summary(df$cwrb_suffix_qualifier)

require(ggplot2)
lay$soc_estimate <- lay$orgc_value_avg*lay$bdws_value_avg
ggplot(lay, aes(soc_estimate)) +
  geom_density()
#takes a while:
#ggplot(lay, aes(soc_estimate, fill=orgc_profile_code)) +
#  stat_density(position="stack")
```

##Explore N and P data
```{r}
summary(as.numeric(as.character(nf$Nmin_g_m2_yr_O_mean)))
summary(as.numeric(as.character(nf$Nmin_g_m2_yr_A_mean)))
summary(as.numeric(as.character(nf$Nmin_g_m2_yr_OA_mean))) #g/m2/horizon
summary(pf$Resin.Pi) #mg P/kg

hist(as.numeric(as.character(nf$Nmin_g_m2_yr_O_mean)), xlim = c(0,100), breaks=100, xlab=expression("Nmin (g/m2/y O horizon)"))
hist(as.numeric(as.character(pf$Resin.Pi)), xlim = c(0,200), breaks=100, xlab=expression("Resin P (mg/kg)"))

require(ggplot2) ##fix margin of legend in this figure...generally cleanup...3d or semi-transparent
ggplot(nf, aes(as.numeric(as.character(nf$Nmin_g_m2_yr_O_mean)))) +
  geom_density()
ggplot(pf, aes(pf$Resin.Pi)) +
  geom_density()

#pdf(file = "/Users/rzabramoff/Dropbox (Climate)/External Collaborations/ISCN/TopsoilNMin.pdf")
ggplot(nf, aes(NminNum, fill=LandUseType)) + #fix labs
  stat_density(position="identity", alpha=0.7) +
  xlim(-10,60) +
  xlab("Topsoil N mineralization (g/m2/y)") #OA horizon in caption
#dev.off()

#ggplot(pf, aes(pf$Resin.Pi, fill=LandUseType)) + #fix labs
#  stat_density(position="stack") +
#  xlim(-10,60) +
#  xlab("Topsoil Resin P (mg/kg)") #OA horizon in caption
```
